#!/usr/bin/env python
# -*- coding: utf-8 -*-

import multiprocessing
import time

import SDS.components.dm.dummydialoguemanager as DummyDM

from SDS.components.hub.messages import Command, SLUHyp, DMDA
from SDS.utils.exception import DMException


class DM(multiprocessing.Process):
    """DM accepts N-best list hypothesis or a confusion network generated by an SLU component.
    The result of this component is an output dialogue act.

    When the component receives an SLU hypothesis then it immediately responds with an dialogue act.

    This component is a wrapper around multiple dialogue managers which handles multiprocessing
    communication.
    """

    def __init__(self, cfg, commands, slu_hypotheses_in, dialogue_act_out):
        multiprocessing.Process.__init__(self)

        self.cfg = cfg
        self.commands = commands
        self.slu_hypotheses_in = slu_hypotheses_in
        self.dialogue_act_out = dialogue_act_out

        self.dm = None
        if self.cfg['DM']['type'] == 'Dummy':
            self.dm = DummyDM.DummyDM(cfg)
        else:
            raise TextHubEception('Unsupported dialogue manager: %s' % self.cfg['DM']['type'])

    def process_pending_commands(self):
        """Process all pending commands.

        Available aio_com:
          stop() - stop processing and exit the process
          flush() - flush input buffers.
            Now it only flushes the input connection.

        Return True if the process should terminate.
        """

        if self.commands.poll():
            command = self.commands.recv()
            if self.cfg['DM']['debug']:
                self.cfg['Logging']['system_logger'].debug(command)

            if isinstance(command, Command):
                if command.parsed['__name__'] == 'stop':
                    return True

                if command.parsed['__name__'] == 'flush':
                    # discard all data in in input buffers
                    while self.slu_hypotheses_in.poll():
                        data_in = self.slu_hypotheses_in.recv()

                    self.dm.flush()

                    return False

        return False

    def read_slu_hypotheses_write_dialogue_act(self):
        # read SLU hypothesis
        while self.slu_hypotheses_in.poll():
            # read SLU hypothesis
            data_slu = self.slu_hypotheses_in.recv()

            if isinstance(data_slu, SLUHyp):
               self.dm.da_in(data_slu.hyp)
               da = self.dm.da_out()

               self.dialogue_act_out.send(DMDA(da))
               self.commands.send(Command('dm_generated()', 'DM', 'HUB'))

            elif isinstance(data_slu, Command):
                cfg['Logging']['system_logger'].info(data_slu)
            else:
                raise DMException('Unsupported input.')

    def run(self):
        self.recognition_on = False

        while 1:
            time.sleep(self.cfg['Hub']['main_loop_sleep_time'])

            # process all pending commands
            if self.process_pending_commands():
                return

            # process the incoming SLU hypothesis
            self.read_slu_hypotheses_write_dialogue_act()
