#!/bin/bash

cd ..

./vhub.py -c \
    ./PublicTransportInfoEN/ptien.cfg \
    ./PublicTransportInfoEN/ptien_hdc_slu.cfg \
    ./PublicTransportInfoEN/google.cfg \
    ./PublicTransportInfoEN/voicerss.cfg \
    ../resources/private/devel.cfg \
    ../resources/private/google_directions.cfg \
