#!/bin/bash

vhub_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
pushd $vhub_dir

for A in {1..1000}
do

  ./vhub.py -n 5 -c \
    ./PublicTransportInfoEN/ptien.cfg \
    ./PublicTransportInfoEN/ptien_hdc_slu.cfg \
    ../resources/private/default.cfg \
    ../resources/private/ext-277278100.cfg  \
    ./PublicTransportInfoEN/google.cfg \
    ./PublicTransportInfoEN/voicerss.cfg \
    ./PublicTransportInfoEN/kaldi.cfg \
    ../resources/private/vystadial-code-server.cfg \

done

popd

