#!/bin/bash

cd ..

./vhub.py -c \
    ./PublicTransportInfoEN/ptien.cfg \
    ./PublicTransportInfoEN/ptien_hdc_slu.cfg \
    ./PublicTransportInfoEN/private_ext.cfg  \
    ./PublicTransportInfoEN/google.cfg \
