#!/bin/bash

cd ..

./vhub.py -c \
    ./PublicTransportInfoEN/ptien.cfg \
    ./PublicTransportInfoEN/ptien_hdc_slu.cfg \
    ../resources/private/devel.cfg  \
    ./PublicTransportInfoEN/google.cfg \
    ./PublicTransportInfoEN/voicerss.cfg \
    ./PublicTransportInfoEN/hclg/kaldi.cfg \
    ./PublicTransportInfoEN/voicerss.cfg \
