#!/bin/bash

vhub_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
pushd $vhub_dir 

./thub.py -c ./PublicTransportInfoCS/ptics.cfg ./PublicTransportInfoCS/google.cfg ./PublicTransportInfoCS/ptics_hdc_slu.cfg ../resources/except_hook.cfg -t

popd
