#!/bin/bash

export LANG=en_US.UTF-8
export LC_ALL="$LANG"
export LANGUAGE="$LANG"


vhub_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
pushd $vhub_dir 

./thub.py -c ./PublicTransportInfoCS/ptics.cfg ./PublicTransportInfoCS/google.cfg -t

popd
