#!/bin/bash

pushd ..

for A in {1..1000}
do
    ./vhub.py -n 10 -c ./PublicTransportInfoCS/ptics.cfg ./PublicTransportInfoCS/ptics_live.cfg ../resources/private/ext-800899998b2.cfg ./PublicTransportInfoCS/kaldi.cfg ./PublicTransportInfoCS/nfs.cfg
done

popd

