#!/bin/bash

vhub_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
pushd $vhub_dir 

for A in {1..1000}
do
    ./vhub.py -n 10 -c ./PublicTransportInfoCS/ptics.cfg ./PublicTransportInfoCS/ptics_live.cfg ../resources/private/ext-800899998b1.cfg ./PublicTransportInfoCS/kaldi.cfg ./PublicTransportInfoCS/nfs.cfg ./PublicTransportInfoCS/ptics_hdc_slu.cfg
done

popd

