#!/bin/bash

pushd ..

for A in {1..1000}
do
    ./vhub.py -n 20 -c ./PublicTransportInfoCS/ptics.cfg ./PublicTransportInfoCS/ptics_live.cfg ../resources/private/ext-vystadial-277278104.cfg ./PublicTransportInfoCS/kaldi.cfg ./PublicTransportInfoCS/nfs.cfg 
done

popd

