#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $MYDIR/..

./wthub.py -p 8124 -c ./PublicTransportInfoCS/ptics.cfg ./PublicTransportInfoCS/ptics_hdc_slu.cfg  ./PublicTransportInfoCS/ptics_wthub.cfg -t
