# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alex/components/hub/wsio_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alex/components/hub/wsio_messages.proto',
  package='cz.cuni.mff.ufal.alex',
  serialized_pb='\n\'alex/components/hub/wsio_messages.proto\x12\x15\x63z.cuni.mff.ufal.alex\"b\n\x0c\x43lientToAlex\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06speech\x18\x02 \x01(\x0c\x12\x10\n\x08location\x18\x03 \x01(\t\x12#\n\x1b\x63urrently_playing_utterance\x18\x04 \x01(\x05\"\xa4\x02\n\x0c\x41lexToClient\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.cz.cuni.mff.ufal.alex.AlexToClient.Type\x12\x0e\n\x06speech\x18\x02 \x01(\x0c\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x12\n\nasr_result\x18\x04 \x01(\t\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\x0b\n\x03seq\x18\x06 \x01(\x05\x12\x14\n\x0cutterance_id\x18\x07 \x01(\x05\"l\n\x04Type\x12\n\n\x06SPEECH\x10\x00\x12\x10\n\x0cSPEECH_BEGIN\x10\x01\x12\x0e\n\nSPEECH_END\x10\x02\x12\x11\n\rSYSTEM_PROMPT\x10\x03\x12\x0e\n\nASR_RESULT\x10\x04\x12\x13\n\x0f\x46LUSH_OUT_AUDIO\x10\x05\"\x9d\x01\n\tPingProto\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12;\n\x06status\x18\x02 \x01(\x0e\x32+.cz.cuni.mff.ufal.alex.PingProto.StatusType\x12\x0b\n\x03key\x18\x03 \x01(\t\"8\n\nStatusType\x12\r\n\tAVAILABLE\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x12\x11\n\rSHUTTING_DOWN\x10\x02\"\xab\x01\n\x14WSRouterRequestProto\x12>\n\x04type\x18\x01 \x01(\x0e\x32\x30.cz.cuni.mff.ufal.alex.WSRouterRequestProto.Type\x12.\n\x04ping\x18\x02 \x01(\x0b\x32 .cz.cuni.mff.ufal.alex.PingProto\"#\n\x04Type\x12\x08\n\x04PING\x10\x00\x12\x11\n\rROUTE_REQUEST\x10\x01\"9\n\x1cWSRouterRoutingResponseProto\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t')



_ALEXTOCLIENT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='cz.cuni.mff.ufal.alex.AlexToClient.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPEECH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPEECH_BEGIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPEECH_END', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_PROMPT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASR_RESULT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUSH_OUT_AUDIO', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=351,
  serialized_end=459,
)

_PINGPROTO_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='cz.cuni.mff.ufal.alex.PingProto.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AVAILABLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTTING_DOWN', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=563,
  serialized_end=619,
)

_WSROUTERREQUESTPROTO_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='cz.cuni.mff.ufal.alex.WSRouterRequestProto.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUTE_REQUEST', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=758,
  serialized_end=793,
)


_CLIENTTOALEX = _descriptor.Descriptor(
  name='ClientToAlex',
  full_name='cz.cuni.mff.ufal.alex.ClientToAlex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cz.cuni.mff.ufal.alex.ClientToAlex.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speech', full_name='cz.cuni.mff.ufal.alex.ClientToAlex.speech', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='cz.cuni.mff.ufal.alex.ClientToAlex.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currently_playing_utterance', full_name='cz.cuni.mff.ufal.alex.ClientToAlex.currently_playing_utterance', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=164,
)


_ALEXTOCLIENT = _descriptor.Descriptor(
  name='AlexToClient',
  full_name='cz.cuni.mff.ufal.alex.AlexToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cz.cuni.mff.ufal.alex.AlexToClient.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speech', full_name='cz.cuni.mff.ufal.alex.AlexToClient.speech', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_prompt', full_name='cz.cuni.mff.ufal.alex.AlexToClient.system_prompt', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asr_result', full_name='cz.cuni.mff.ufal.alex.AlexToClient.asr_result', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='cz.cuni.mff.ufal.alex.AlexToClient.priority', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='cz.cuni.mff.ufal.alex.AlexToClient.seq', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='utterance_id', full_name='cz.cuni.mff.ufal.alex.AlexToClient.utterance_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ALEXTOCLIENT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=459,
)


_PINGPROTO = _descriptor.Descriptor(
  name='PingProto',
  full_name='cz.cuni.mff.ufal.alex.PingProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='cz.cuni.mff.ufal.alex.PingProto.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='cz.cuni.mff.ufal.alex.PingProto.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='cz.cuni.mff.ufal.alex.PingProto.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PINGPROTO_STATUSTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=462,
  serialized_end=619,
)


_WSROUTERREQUESTPROTO = _descriptor.Descriptor(
  name='WSRouterRequestProto',
  full_name='cz.cuni.mff.ufal.alex.WSRouterRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cz.cuni.mff.ufal.alex.WSRouterRequestProto.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping', full_name='cz.cuni.mff.ufal.alex.WSRouterRequestProto.ping', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WSROUTERREQUESTPROTO_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=622,
  serialized_end=793,
)


_WSROUTERROUTINGRESPONSEPROTO = _descriptor.Descriptor(
  name='WSRouterRoutingResponseProto',
  full_name='cz.cuni.mff.ufal.alex.WSRouterRoutingResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='cz.cuni.mff.ufal.alex.WSRouterRoutingResponseProto.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='cz.cuni.mff.ufal.alex.WSRouterRoutingResponseProto.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=795,
  serialized_end=852,
)

_ALEXTOCLIENT.fields_by_name['type'].enum_type = _ALEXTOCLIENT_TYPE
_ALEXTOCLIENT_TYPE.containing_type = _ALEXTOCLIENT;
_PINGPROTO.fields_by_name['status'].enum_type = _PINGPROTO_STATUSTYPE
_PINGPROTO_STATUSTYPE.containing_type = _PINGPROTO;
_WSROUTERREQUESTPROTO.fields_by_name['type'].enum_type = _WSROUTERREQUESTPROTO_TYPE
_WSROUTERREQUESTPROTO.fields_by_name['ping'].message_type = _PINGPROTO
_WSROUTERREQUESTPROTO_TYPE.containing_type = _WSROUTERREQUESTPROTO;
DESCRIPTOR.message_types_by_name['ClientToAlex'] = _CLIENTTOALEX
DESCRIPTOR.message_types_by_name['AlexToClient'] = _ALEXTOCLIENT
DESCRIPTOR.message_types_by_name['PingProto'] = _PINGPROTO
DESCRIPTOR.message_types_by_name['WSRouterRequestProto'] = _WSROUTERREQUESTPROTO
DESCRIPTOR.message_types_by_name['WSRouterRoutingResponseProto'] = _WSROUTERROUTINGRESPONSEPROTO

class ClientToAlex(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTTOALEX

  # @@protoc_insertion_point(class_scope:cz.cuni.mff.ufal.alex.ClientToAlex)

class AlexToClient(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALEXTOCLIENT

  # @@protoc_insertion_point(class_scope:cz.cuni.mff.ufal.alex.AlexToClient)

class PingProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGPROTO

  # @@protoc_insertion_point(class_scope:cz.cuni.mff.ufal.alex.PingProto)

class WSRouterRequestProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WSROUTERREQUESTPROTO

  # @@protoc_insertion_point(class_scope:cz.cuni.mff.ufal.alex.WSRouterRequestProto)

class WSRouterRoutingResponseProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WSROUTERROUTINGRESPONSEPROTO

  # @@protoc_insertion_point(class_scope:cz.cuni.mff.ufal.alex.WSRouterRoutingResponseProto)


# @@protoc_insertion_point(module_scope)
