database = {
  "addr": {
      "alexander street": ["alexander street","alexander"],
      "art square": ["art square", "art"],
      "bridge nine": ["bridge nine","bridge"],
      "cascade road": ["cascade road", "cascade"],
      "castle loop": ["castle loop","castle", "loop"],
      "dontcare": ["dontcare",],
      "fountain road": ["fountain road","foutain"],
      "main square": ["main square",],
      "main street": ["main street",],
      "middle road": ["middle road",],
      "north road": ["north road",],
      "park road": ["park road",],
      "red bridge": ["read bridge",],
      "short street": ["short street",],
      "south bridge": ["south bridge",],
      "tower hill road": ["tower hill road","tower"],
      "west loop": ["west loop","west"],
  },

  "area": {
      "central": ["central","centre"],
      "east": ["east",],
      "north": ["north",],
      "riverside": ["riverside",],
      "south": ["south",],
      "west": ["west",],
  },

  "drinks": {
      "beer": ["beer",],
      "cocktails": ["cocktails",],
      "soft drinks": ["soft drinks", "soft"],
      "wine": ["wine",],
  },

  "food": {
      "chinese": ["chinese",],
      "english": ["english",],
      "fish": ["fish",],
      "french": ["french",],
      "indian": ["indian",],
      "italian": ["italian",],
      "russian": ["russian",],
      "snacks": ["snacks",],
  },

  "music": {
      "classical": ["classical",],
      "ethnic": ["ethnic",],
      "folk": ["folk",],
      "jazz": ["jazz",],
      "pop": ["pop",],
      "rap": ["rap",],
      "rock": ["rock",],
  },

  "name": {
      "alexander hotel": ["alexander hotel", "alexander"],
      "art house hotel": ["art house hotel", "art"],
      "bar metropol": ["bar metropol","metropol"],
      "bochka": ["bochka",],
      "buffalo bills": ["buffalo bills", "buffalo", "bills"],
      "cafe blue": ["cafe blue", "blue"],
      "carnaby street": ["carnaby street", "carnaby"],
      "char sue": ["char sue", "char", "sue"],
      "chez sergu": ["chez sergu", "chez", "sue"],
      "cinema": ["cinema",],
      "europa": ["europa",],
      "fountain": ["fountain",],
      "hole in the wall": ["hole in the wall","hole in", "the wall"],
      "hotel president": ["hotel president", "president"],
      "hotel primus": ["hotel primus", "primus"],
      "ice cool": ["ice cool", "ice"],
      "jasons castle": ["jasons castle", "jason"],
      "kings shilling": ["kings shilling", "kings", "shilling"],
      "la garonde": ["la garonde", "garonde"],
      "last": ["last",],
      "loch sole": ["loch sole", "loch", "sole"],
      "main square": ["main square", ],
      "murphys": ["murphys",],
      "museum": ["museum",],
      "noble nest": ["noble nest", "noble", "nest"],
      "number one": ["number one",],
      "park": ["park",],
      "pizza palace": ["pizza palace", "palace"],
      "planters": ["planters",],
      "police station": ["police station", "police"],
      "post office": ["post office", "post"],
      "royal hotel": ["royal hotel", "royal"],
      "saint petersburg": ["saint petersburg", "saint", "petersburg"],
      "siberian tiger": ["siberian tiger", "siberian", "tiger"],
      "steves place": ["steves place", "steves"],
      "taj mahal": ["taj mahal", "taj", "mahal"],
      "the angler": ["the angler", "angler"],
      "the express": ["the express", "express"],
      "the grand": ["the grand", "grand"],
      "the grant": ["the grant", "grant"],
      "the parrot": ["the parrot", "parrot"],
      "the quay": ["the quay", "quay"],
      "the regent": ["the regent", "regent"],
      "tourist information": ["tourist information", "tourist"],
      "ville house": ["ville house", "ville", "house"],
      "westside shopping": ["westside shopping", "westside"],
      "youth hostel": ["youth hostel", "youth", "hostel"],
  },

  "near": {
      "castle": ["castle",],
      "cinema": ["cinema",],
      "fountain": ["fountain",],
      "main square": ["main square", "main", "square"],
      "museum": ["museum",],
      "park": ["park",],
      "police station": ["police station", "police"],
      "post office": ["post office", "post"],
      "railway station": ["railway station", "railway"],
      "river jay": ["river jay", "river", "jay", "riverside"],
      "royal hotel": ["royal hotel", "royal"],
      "tourist information": ["tourist information", "tourist", "information"],
      "tower": ["tower",],
      "westside shopping": ["westside shopping", "westside", "shopping"],
  },

  "phone": {
  },

  "price": {
  },

  "pricerange": {
      "cheap": ["cheap", "cheaper"],
      "expensive": ["expensive", "luxurious"],
      "moderate": ["mid priced", "mid range", "mid", "medium", "midpriced", "midprice", "reasonably priced", "moderate", "moderately"],
  },

  "stars": {
      "1": ["1", "one"],
      "2": ["2", "two"],
      "3": ["3", "three"],
      "4": ["4", "four"],
      "5": ["5", "five"],
  },

  "task": {
      "find": ["find", "looking"],
  },

  "type": {
      "bar": ["bar", "bars"],
      "hotel": ["hotel", "hotels"],
      "restaurant": ["restaurant", "restaurants"],
  },
}
